on: [push, pull_request]

jobs:
  python-lint:
    runs-on: ubuntu-latest
    name: CI workflow
    steps:
    - name: checkout source repo
      uses: actions/checkout@v2

    - name: linting
      uses: programmingwithalex/pylinter@v1.4.2
      with:
        python-root: '.'
        flake8-flags: ''
        mypy-flags: '--ignore-missing-imports'
        fail-on-isort: true